[[packages]]
name = "homebrew"
cmd = ["brew", "bundle", "dump", "--describe", "--file=-"]
filename = "Brewfile"

[[packages]]
name = "vscode"
cmd = ["code", "--list-extensions"]
filename = "extensions.txt"

[[folders]]
parent = ".config"
children = [
    "fish",
    "omf",
    "resin",
    "neofetch",
    "zathura",
    "raycast/script-commands",
    "nvim"
]

[[folders]]
parent = "."
children = [
    "Library/Application Support/Code/User/snippets",
    "Library/Application Support/com.mitchellh.ghostty",
]

[[files]]
parent = ".config"
children = ["gh/config.yml"]

[[files]]
parent = "."
children = [
    ".gitconfig",
    ".docker/config.json",
    "Library/Application Support/Code/User/keybindings.json",
    "Library/Application Support/Code/User/settings.json",
    ".gnupg/gpg-agent.conf",
    ".rustup/settings.toml",
]
