[v1]
"cargo-edit 0.13.7 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-add",
    "cargo-rm",
    "cargo-set-version",
    "cargo-upgrade",
]
"cargo-update 18.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-install-update",
    "cargo-install-update-config",
]
"resin 1.6.6 (path+file:///Users/matt/src/gleich/resin)" = ["resin"]
