[tool.poetry]
name = "latest"
version = "0.1.0"
description = "Get the latest config for my machine"
authors = ["Matthew Gleich <email@mattglei.ch>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
loguru = "^0.5.3"

[tool.poetry.dev-dependencies]
autopep8 = "^1.5.4"
black = "^20.8b1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
